### ISSUE TITLE
mote does not support brightness

### ISSUE THREAD

**Issue by dglaude** [pimoroni/mote#19]
I just noticed that while the APA102 on the mote stick support brightness but the mote library does not expose this. Maybe because the serial protocol does not?

Is there a plan to add this?
Else what is the limitation?

**Comment by Gadgetoid** [comment]
The Mote firmware doesn't expose this feature at all, since the 5bit brightness setting on the APA102s is at best useless and at worst actively thwarts things like channel-dependent gamma correction. I'm planning to remove support for it in Mote pHAT in favour of simply scaling the colour values as part of the suite of changes in: https://github.com/pimoroni/mote/issues/18
