### ISSUE TITLE
Is there any support for Hyperion?

### ISSUE THREAD

**Issue by iCarl** [pimoroni/mote#23]
Will there be any support for Hyperion as you said in bilge tank 026?

**Comment by Gadgetoid** [comment]
There was definitely some work toward this end, but I don't know how far it got. See: https://hyperion-project.org/threads/pimoroni-mote-usb-led-apa102.509/

**Comment by dglaude** [comment]
Paul Webster (@paulwebster) made this:
https://github.com/PaulWebster/artnet-unicorn-hat

I (@DavidGlaude) tested and documented the "install on OSMC" section with
some success
https://gist.github.com/dglaude/c782305c4004f750184630acac67f2bf

I did not test with a movie because I had no content handy and I am new to
OSMC, but I tested with Hyperion configuration tool.
Also one of my four mote stick is broken, so it would have require to
change the proposed 4 stick configuration.

Latter lost in ArtNet and developing a server for unicornHD HAT.
And I want to do a Blinkt! version, but I need to find a solution to
transport the light from the Blinkt! to 8 location behind my TV... maybe
plastic tube used for fish tank.

Please, this require traction as it has been a long requested feature.
Bring Sandy to do a tutorial and rebuild the BilgeTank to promote this
usage... :-)
And Pimoroni will sell hundred of mote (that code is for the USB version,
Paul does not have a mote pHAT and I did not find mine in my mess... but it
should be easy to patch.

2017-11-10 19:38 GMT+01:00 Philip Howard <notifications@github.com>:

**Comment by PaulWebster** [comment]
If you use my version of Artnet-Server then it works fine with Hyperion.
Indeed there are a couple of sample Hyperion config files included in it.
Ideally should move the hard-coded config out of the Python code and to command line or config file.
Also, it assumes that each of the LED chains has same number of LEDs ... which is probably OK for Mote sticks but really should be generalised (eg for Day when Pimoroni ships sticks of different lengths or people plug in their own APA102 ribbons.

FYI 4 sticks of 16 LEDs not really enough for screen of 40-inch plus.
